[package]
name = "grey_crypt"
version = "0.0.1"
authors = [ "John Quigley <jmquigs@gmail.com>" ]

[dependencies]
toml = "0.1"
uuid = "0.1"
rust-crypto = "0.2.31"
rand = "0.3.8"
rustc-serialize = "0.3"
getopts = "0.2"
glob = "*"
